---
 
- name: Create an ec2 instance
  hosts: web
  gather_facts: false
 
  tasks:
 
    - name: Create an ec2 instance
      ec2:
	 key_name: "{{ keypair }}"
         group: "{{ security_group }}"
         instance_type: "{{ instance_type }}"
         image: "{{ ami }}"
         wait: true
         region: "{{ region }}"
         count: 1
         vpc_subnet_id: "{{ vpc_subnet_id }}"
         assign_public_ip: yes
    register: ec2
